plugins {
    id 'java'
}

group = 'cz.cvut.kbss.annotace'
version = ''

repositories {
    mavenCentral()
}

dependencies {
    implementation project(":api")
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
    jvmArgs "-Djava.library.path=/Users/matej/actual/projekt3/nové repo/annotace"
    systemProperty 'morphodita.model', '/Users/matej/actual/projekt3/nové repo/annotace/czech-morfflex2.1-pdtc2.0-250909.tagger'

    testLogging {
        showStandardStreams = true   // uvidíš System.out z testů
    }
    doFirst {
        println ">>> jvmArgs testu: ${jvmArgs}"
    }
}