plugins {
    id 'java'
}

group = 'cz.cvut.kbss.annotace'
version = ''

repositories {
    mavenCentral()
}

dependencies {
    implementation project(":api")
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}