apply plugin: "io.spring.dependency-management"

// Note the value should be the directory containing libmorphodita_java.so, not path to the file itself!
//test {
//    systemProperty ("java.library.path", "/path/to/directory/containing/libmorphodita_java.so")
//}

dependencies {
    implementation project(":api")
    implementation project(":lemmatizer-spark")
    implementation project(":lemmatizer-morphodita")
    implementation project(":lemmatizer-LLM")
    implementation project(":testservice")

    testImplementation(libs.junit.params)
    implementation(libs.spring.boot.web)
    testImplementation(libs.spring.boot.test) {
        exclude group: "org.junit.vintage", module: "junit-vintage-engine"
    }
    implementation "cz.cvut.kbss:morphodita:0.0.1"
}

test {
    jvmArgs "--add-opens", "java.base/sun.nio.ch=ALL-UNNAMED", "--add-opens", "java.base/java.nio=ALL-UNNAMED", "--add-opens", "java.base/java.util=ALL-UNNAMED", "--add-opens", "java.base/java.lang=ALL-UNNAMED", "--add-opens", "java.base/java.lang.invoke=ALL-UNNAMED"
}

//--add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED